### ISSUE TITLE
Question on output

### ISSUE THREAD

**Issue by mloning** [hfawaz/cd-diagram#5]
Hi Hassan, 

I've used your code for creating a critical difference diagram and got the following output. Am I misunderstanding something or should that extra line between M4 winner and M4 runner-up not be there?

<img width="835" alt="Screenshot 2020-05-05 at 09 55 53" src="https://user-images.githubusercontent.com/21020482/81536471-858ee000-9363-11ea-993f-4e829eaf7dba.png">

**Comment by hfawaz** [comment]
Hi Markus, 

Thanks for sharing your thoughts. 

Indeed if we were applying Nemenyi test, we should not have such overlapping segments. 

But when using Wilcoxon signed rank test for the post-hoc analysis, this sort of segments could appear since the Wilcoxon method does not take into consideration the average rank. 

In this case, your diagram means that:
- RF-s and M4 runner-up are not significantly different. 
- M4 winner and M4 runner-up are not significantly different. 
- RF-s and M4 winner are significantly different. 

This sort of behavior is described clearly in [this paper](https://dl.acm.org/doi/pdf/10.1145/3182382?download=true), section "HESCA Accuracies on Test Data".

Hope this helps.

**Comment by mloning** [comment]
Thanks the clarification! 

FYI @fkiraly
